### ISSUE TITLE
Trying to run this without vscode jack-in

### ISSUE THREAD

**Issue by slifin** [dustingetz/missionary-quickstart#3]
So I'm running shadow-cljs watch dev on the terminal and I get 

```
[:dev] Build failure:
The required namespace "user" is not available.
```

I think I did get this intermittently working the other day with heavy customisation by adding something similar to 
https://shadow-cljs.github.io/docs/UsersGuide.html#_using_deps_edn_with_custom_repl_intialization I'll see if I can get a reliable replication of that, using Cursive for context

**Comment by slifin** [comment]
huh, adding `:deps true` to shadow-cljs.edn seems to work

**Comment by slifin** [comment]
Steps I'm using are -> install shadow-cljs globally -> add :deps true to shadow-cljs.edn -> execute `shadow-cljs watch dev` -> setup remote repl in cursive and connect using .nport-port -> when in the repl type (shadow/repl :dev) -> open web browser tab for shadow -> type (js/alert "hi") in the repl to ensure connection

**Comment by dustingetz** [comment]
i will attempt to reproduce with cursive and make the change

**Comment by dustingetz** [comment]
https://github.com/dustingetz/missionary-quickstart/commit/386026e1535a44dcc5d2e663005b4ae788b7a581
